PREFIX ex: <http://example.org/vocabulary/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

# Vybere všechny dvojice lesson1 a lesson2, které se odehrávají ve stejném časovém slotu a mají stejný předmět, vypíše lesson id a jméno předmětu.

SELECT DISTINCT ?lesson1ID ?lesson2ID ?subjectName
WHERE {
  	?lesson1 a ex:Lesson ;
  		ex:TakesTime ?timeslot ;
  		ex:IsTaught ?subject ;
    	ex:LessonID ?lesson1ID .
  
  	?lesson2 a ex:Lesson ;
  		ex:TakesTime ?timeslot ;
  		ex:IsTaught ?subject ;
  		ex:LessonID ?lesson2ID .
  	
   	?subject a ex:Subject ;
    	ex:SubjectName ?subjectName . 

    FILTER (STR(?lesson1ID) < STR(?lesson2ID))
}