PREFIX ex: <http://example.org/vocabulary/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

# Vybere id lesson1 lesson2, 

SELECT ?lesson1ID ?lesson2ID ?subjectName
WHERE {
  	?lesson1 a ex:Lesson ;
  		ex:Time ?timeslot ;
  		ex:IsTaught ?subject ;
    	ex:LessonID ?lesson1ID .

  	?lesson2 a ex:Lesson ;
  		ex:Time ?timeslot ;
  		ex:IsTaught ?subject ;
  		ex:LessonID ?lesson2ID .
  	
   	?subject a ex:Subject ;
    	ex:SubjectName ?SubjectName . 
}